### ISSUE TITLE
tests fail arbitrarily on travis

### ISSUE THREAD

**Issue by lepmik** [CINPLA/expipe#18]
sometimes you have to build on travis multiple times to get the the tests pass. Maybe something with pyrebase?

**Comment by espenhgn** [comment]
Due to some seg-fault? I have issues with LFPy testing as well: https://github.com/LFPy/LFPy/issues/23 
In my case I could sometimes reproduce it on an Ubuntu VM, so I don't think it has anything to do with TravisCI

**Comment by miladh** [comment]
Seems to have been resolved. Reopen if not.

**Comment by espenhgn** [comment]
@miladh what's the fix?

**Comment by miladh** [comment]
I didn't do anything, but it seems to work fine now (other things are failing at the moment)
