### ISSUE TITLE
Add support for registering subjects or remove them from actions?

### ISSUE THREAD

**Issue by dragly** [CINPLA/expipe#25]
The fact that we (CINPLA) have a subject-registry project made me realize that we never added proper support for subjects in the data model. Originally, this was intended to be stored in a separate root-level node called "subjects".

Our current use shows that we need a few things for subjects (subjects are currently implemented by having each subject as an action and adding modules to that action):

- share subjects across projects
- store per-project information about a subject
- store complex information about subjects (modules)

Taking a step back, I realize that this type of information is not specific to subjects, and not all experiments/simulations study something that translates well to a "subject". We want to store information about other "things" in a similar manner, such as equipment and cells, depending on the type of experiment.

To generalize, we might want to use something a bit more agnostic, like an "entity". Then, on a database level, what we want to do is:

- identify a subject/entity across projects
- add project-specific information about an entity
- maybe add global information about an entity (could be dangerous if information is changed/added in incompatible ways)
- add information to an action about the use of a specific entity

One way to solve this could be to add `entity` and `entity_modules` to the root level, similarly to `actions` and `action_modules`.

However, one of the benefits of our current design is that we add information to an action about anything by making a template into a module. In this sense, a subject/entity is just a template.

Perhaps we should just consider removing the subject list in actions and instead add each subject as a module? That would simplify the design greatly and allow different groups to adapt the system to their needs.

**Comment by dragly** [comment]
After a quick discussion with @lepmik, we concluded with the following:

- we generalize subjects to templates
- each subject is stored as a template and maintained over time
- each time an action using a subject is registered, the user adds a module based on the subject's template
- templates should lose their current keys (they are hard to make and maintain) and instead have autogenerated keys
- or, the we should at least not depend on template keys to be user-friendly
- templates should have tags, such as "subject" which are easily used for filtering in the browser
- if common templates are added in a project, this should be added as functionality in a plugin, for instance by having a project module called "default_templates", which is accessed by the plugin when uploading a new action. The plugin finds the default templates based on for instance the action type and adds these to the action.

**Comment by lepmik** [comment]
Subjects are now handeled as Entities which is a object on par with Actions
