### ISSUE TITLE
action data path main gives bad path

### ISSUE THREAD

**Issue by lepmik** [CINPLA/expipe#59]
for example 
```python
actions['001-181220-2'].data_path('main')
>>> PosixPath('/projects/ec109/Sarah/projects/hpc-social-nwb/actions/001-181220-2/data/actions/001-181220-2/data/main.nwb')
```

**Comment by dragly** [comment]
What is bad about the path? It looks like `"main"` has just been assigned to the path `"main.nbw"` previously?

In other words, that something like this has been run before:
```
actions['001-181220-2'].data['main'] = "main.nbw"
```

**Comment by lepmik** [comment]
It's bad in the sense that `actions/001-181220-2/data` is repeated in the path :)

**Comment by lepmik** [comment]
No you are right, its been generated in the wrong way @alejoe91 this is a expipe-plugin-cinpla issue. Closing this here
